In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 1, 1])
arr2 = np.array([0, 1, 1])
print(np.mean(arr1 == arr2))

0.6666666666666666


In [5]:
arr = np.array([1, 2, 3])
print(np.clip(arr, 1e-5, 1-1e-5))

[0.99999 0.99999 0.99999]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.clip(arr, 2, 5))

[2 2 3 4 5 5 5 5]


In [11]:
# header files needed
import numpy as np

# sigmoid function
def sigmoid(input):
    return (1 / (1 + np.exp(-input)))

# relu function
def relu(input):
    return np.maximum(0, input)

In [12]:
arr = np.array([1, 2, 3, 4, -1, -2])
print(relu(arr))

[1 2 3 4 0 0]
